### ISSUE TITLE
Error in Readme to run project locally

### ISSUE THREAD

**Issue by Bhavik-Ardeshna** [JuliaLang/www.julialang.org#1207]

**Comment by Bhavik-Ardeshna** [comment]
Clone the repository and `cd` to it. Start julia with `julia --project` and do

```julia
julia> using Pkg; Pkg.instantiate()

julia> using Franklin

julia> newsite("mySite", template="pure-sm")

julia> serve()
→ Initial full pass...
→ evaluating code [...] (learning/code-examples.md)
→ Starting the server...
✓ LiveServer listening on https://localhost:8000/ ...
  (use CTRL+C to shut down)
```

**Comment by Bhavik-Ardeshna** [comment]
```
julia> serve()
 Activating environment at `~/Desktop/Julia/www.julialang.org/Project.toml`
→ Initial full pass...
┌ Franklin Warning: in <jsoc/gsoc/graphs.md>
│ A h-function call '{{fill title}}' (or '{{title}}') has argument 'title' which
│ doesn't match a page variable available in the current scope. It might have
│ been misspelled or should be defined via a '@def title = ...' either
│ locally on the page or globally in 'config.md'.
│ 
│ Relevant pointers:
│ - page variables and {{...}} blocks: https://franklinjl.org/syntax/page-variables/
└
┌ Franklin Warning: in <MLJ.md>
│ Encountered an issue processing 'MLJ.md' in rg/content/jsoc/gsoc.
│ Verify, then re-start the Franklin server.
│ The error is displayed below:
│ Franklin.HTMLBlockError("I found a HBlock that did not match anything, verify '{{< get_param title >}}'")
└
ERROR: Franklin.HTMLBlockError("I found a HBlock that did not match anything, verify '{{< get_param title >}}'")
Stacktrace:
 [1] process_file(::Symbol, ::Pair{String,String}, ::String, ::Vararg{Any,N} where N) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/file_utils.jl:88
 [2] fd_fullpass(::NamedTuple{(:other, :infra, :md, :html, :literate),NTuple{5,Dict{Pair{String,String},Float64}}}) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/franklin.jl:240
 [3] serve(; clear::Bool, verb::Bool, port::Int64, single::Bool, prerender::Bool, nomess::Bool, is_final_pass::Bool, no_fail_prerender::Bool, eval_all::Bool, silent::Bool, cleanup::Bool, on_write::Franklin.var"#231#234", log::Bool, host::String, show_warnings::Bool, launch::Bool) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/franklin.jl:118
 [4] serve() at /home/user/.julia/packages/Franklin/X69Nd/src/manager/franklin.jl:66
 [5] top-level scope at REPL[9]:1
caused by [exception 1]
Franklin.HTMLBlockError("I found a HBlock that did not match anything, verify '{{< get_param title >}}'")
Stacktrace:
 [1] qualify_html_hblocks(::Array{Franklin.OCBlock,1}) at /home/user/.julia/packages/Franklin/X69Nd/src/parser/html/blocks.jl:69
 [2] convert_html(::String) at /home/user/.julia/packages/Franklin/X69Nd/src/converter/html/html.jl:20
 [3] map at ./tuple.jl:159 [inlined]
 [4] map at ./tuple.jl:160 [inlined]
 [5] write_page(::String, ::String; head::String, pgfoot::String, foot::String) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/write_page.jl:96
 [6] convert_and_write(::String, ::String, ::String, ::String, ::String, ::String) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/write_page.jl:198
 [7] process_file_err(::Symbol, ::Pair{String,String}, ::String, ::String, ::String, ::Float64) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/file_utils.jl:113
 [8] process_file(::Symbol, ::Pair{String,String}, ::String, ::Vararg{Any,N} where N) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/file_utils.jl:75
 [9] fd_fullpass(::NamedTuple{(:other, :infra, :md, :html, :literate),NTuple{5,Dict{Pair{String,String},Float64}}}) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/franklin.jl:240
 [10] serve(; clear::Bool, verb::Bool, port::Int64, single::Bool, prerender::Bool, nomess::Bool, is_final_pass::Bool, no_fail_prerender::Bool, eval_all::Bool, silent::Bool, cleanup::Bool, on_write::Franklin.var"#231#234", log::Bool, host::String, show_warnings::Bool, launch::Bool) at /home/user/.julia/packages/Franklin/X69Nd/src/manager/franklin.jl:118
 [11] serve() at /home/user/.julia/packages/Franklin/X69Nd/src/manager/franklin.jl:66
 [12] top-level scope at REPL[9]:1
```

Error while running project without cmg
```
julia> newsite("mySite", template="pure-sm")
``

**Comment by Bhavik-Ardeshna** [comment]
#1208

**Comment by KristofferC** [comment]
The error is because a page somewhere is faulty, and that page should be fixed. Could be the page in the warning:

```
│ Encountered an issue processing 'MLJ.md' in rg/content/jsoc/gsoc.
```

**Comment by Bhavik-Ardeshna** [comment]
Ok sir ...I got it.
I am working on that issue

**Comment by Bhavik-Ardeshna** [comment]
Sir @KristofferC remove graphs.md but its showing one more warning about title
```
# {{< get_param title >}}
```

```
julia> serve()
 Activating environment at `~/Desktop/Julia/www.julialang.org/Project.toml`
→ Initial full pass...
┌ Franklin Warning: in <MLJ.md>
│ Encountered an issue processing 'MLJ.md' in rg/content/jsoc/gsoc.
│ Verify, then re-start the Franklin server.
│ The error is displayed below:
│ Franklin.HTMLBlockError("I found a HBlock that did not match anything, verify '{{< get_param title >}}'")
└
```
Any specific title need to give here plz provide

**Comment by Bhavik-Ardeshna** [comment]
```
julia> serve()
 Activating environment at `~/Desktop/Julia/www.julialang.org/Project.toml`
→ Initial full pass...
┌ Franklin Warning: in <menu2.md>
│ Encountered an issue processing 'menu2.md' in julialang.org/mySite.
│ Verify, then re-start the Franklin server.
│ The error is displayed below:
│ Franklin.LxObjError("Command or environment '\\baz' was used before it was\ndefined.")
└
ERROR: Franklin.LxObjError("Command or environment '\\baz' was used before it was\ndefined.")
```

I resolved some error in ```/content/jsoc/gsoc``` and also delete ```graphs.md```
But still showing issue

**Comment by KristofferC** [comment]
`julialang.org/mySite`, the issue there seems to be the `mySite` that you generated earlier. You can probably just remove that directory.

**Comment by logankilpatrick** [comment]
Hey @Bhavik-Ardeshna looks like the issue is that you generated a new site within the existing site repo as Kristoffer pointed out. I verified that the steps in the readme do in fact run the site. Thanks for this issue and if you think things could me improved, please open a PR.
